title: Playing a video with omxplayer
hero_image: images/banner.png
description: Playing a video on the Raspberry Pi with OMX Player
original_url:
theme: cc-prototype
duration: 1
listed: false
copyedit: false
interests: ""
technologies: "raspberry pi"
steps:
  - title: Playing video with OMX Player
