title: Playing a video with OMXPlayer
hero_image: images/banner.png
description: Playing a video on the Raspberry Pi with OMXPlayer
original_url:
theme: cc-prototype
duration: 1
listed: false
copyedit: true
interests: ""
technologies: "raspberry pi"
steps:
  - title: Playing video with OMXPlayer
